version: '3.5'

services:

  api:
    container_name: nest_api
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432
