# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  BUCKET: ${{ secrets.BUCKET }}
  ENV_AMB: ${{ secrets.ENV_AMB }}
  KEY_ID: ${{ secrets.ENV_AMB }}
  MONGOPROD: ${{ secrets.MONGOPROD }}
  MONGOQA: ${{ secrets.MONGOQA }}
  REGIONAWS: ${{ secrets.REGIONAWS }}
  STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
on:
  push:
    branches: [ "master","development" ]
  pull_request:
    branches: [ "master","development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.12.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Get secret from base64
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        BUCKET: ${{ secrets.BUCKET }}
        ENV_AMB: ${{ secrets.ENV_AMB }}
        KEY_ID: ${{ secrets.ENV_AMB }}
        MONGOPROD: ${{ secrets.MONGOPROD }}
        MONGOQA: ${{ secrets.MONGOQA }}
        REGIONAWS: ${{ secrets.REGIONAWS }}
        STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
        
      run: |
        echo import certificate from secrets and regenerate the file
        echo $ENV_AMB | base64 -d > $RUNNER_TEMP/my_production.keystore
        
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:e2e
