# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  BUCKET: ${{ secrets.BUCKET }}
  ENV_AMB: ${{ secrets.ENV_AMB }}
  KEY_ID: ${{ secrets.ENV_AMB }}
  MONGOPROD: ${{ secrets.MONGOPROD }}
  MONGOQA: ${{ secrets.MONGOQA }}
  REGIONAWS: ${{ secrets.REGIONAWS }}
  STORAGE_TYPE: ${{ secrets.STORAGE_TYPE }}
on:
  push:
    branches: [ "master","development" ]
  pull_request:
    branches: [ "master","development" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_VARIABLE: JOB
    steps:
      - name: Run Commands with various variables
        if: ${{ env.ENV_AMB == 'QA' }} # Example using context env
        env:
          STEP_VARIABLE: STEP
        run: |
          echo "Hello World"
          echo "This is the $ACCESS_KEY environment variable"
